simplify capture of clone vars
DataDog/scipio pull request #43
Opened 2020-09-09 17:36 UTC by sitano

Instead of doing

```
let x = Rc<...>(...);
let f = || x.clone();
let f2 = f.clone()
```

It can be done with anonymous function like this:

```
let second = local_ex
            .spawn_into(
                (|f: Rc<RefCell<bool>>, s: Rc<RefCell<bool>>| {
                    async move {
                       ...
                    }
                })(first_started.clone(), second_status.clone()),
                tq2,
            )
            .unwrap();

```

Rust can't derive type information for (f, s) himself
so it's required to be stated it explicitly as in
`|f: Rc<RefCell<bool>>, s: Rc<RefCell<bool>>|` instead of `|f, s|`.

However, there is a popular macro `enclose!` that does the job.

```
  enclose! { (x, y)
    async move {
    ...
    }
  }
```

### What does this PR do?

A brief description of the change being made with this pull request.

### Motivation

What inspired you to submit this pull request?

### Related issues

A list of issues either fixed, containing architectural discussions, otherwise relevant
for this Pull Request.

### Additional Notes

Anything else we should know when reviewing?

### Checklist

[] I have added unit tests to the code I am submitting
[] My unit tests cover both failure and success scenarios
[] If applicable, I have discussed my architecture
[] The new code I am adding is formatted using `rustfmt`

2020-09-09 17:36 UTC, sitano commented
@glommer I am sorry GitHub does not allow reopening force pushed commits.

2020-09-11 14:34 UTC, glommer requested changes

2020-09-11 14:38 UTC, sitano commented on scipio/src/executor.rs
> +
Ok, but all the rest of the code has a new line separating local_ex val and a call to run

2020-09-11 14:45 UTC, sitano commented on scipio/src/executor.rs
> +#[cfg(test)]
exported lib.rs: `pub use enclose::enclose;`
use in tests: `crate::enclose!`

2020-09-11 14:45 UTC, sitano commented on scipio/src/executor.rs
> +use futures::join;
removed. As there is no sense to do a single usage `use` a left `futures::join!`

2020-09-11 14:58 UTC, glommer reviewed
Hi Ivan

Good progress, we are getting ready to merge status here!

As I had said previously, I would like to see a very simple example of some external code using this to make sure we don't break it. Exporting macros is tricky.

something under `examples` that uses this.

The other comment is that this patch is mixing adding enclose with lots of cleanups in which you are changing Task:: to Local.

Those cleanups are very welcome but I would like to see them split at a separate patch. You can leave that for the end if you prefer to only add the example in the next round

2020-09-11 16:39 UTC, sitano commented
@glommer I have added ping pong example:

```
$ cargo build --example ping_pong
$ ./target/debug/examples/ping_pong

right
left
reset
...
```

2020-09-11 16:46 UTC, glommer approved these changes
Ivan, I am approving 960bce3dee3c17268056d8fd3eca32c9921f2a3e

but I would like to see this split in two patches: the first one only with the cleanups like changing task to local, and then on top you can add your enclose.

Please force push a version that does that, and make sure that the diff from 960bce3dee3c17268056d8fd3eca32c9921f2a3e comes empty.

2020-09-11 17:02 UTC, sitano commented
ok!

2020-09-12 14:58 UTC, sitano commented
@glommer split into:

- cleanup: use Local instead of Task::<()>
- clone captured vars for async closures …

2020-09-12 20:48 UTC, merged